### ISSUE TITLE
The data frame image does not show up on 09-loading-data.md

### ISSUE THREAD

**Issue by snamburi3** [smcclatchy/introductory-statistics-with-r#1]
@smcclatchy The data frame image does not show up on the markdown page. 

on line 365, it should be svg instead of png image

```
 ![example data frame](../fig/data-frame.png)
```

https://github.com/smcclatchy/introductory-statistics-with-r/blob/gh-pages/_episodes/09-loading-data.md

**Comment by smcclatchy** [comment]
thanks @snamburi3 it's there now

**Comment by smcclatchy** [comment]
exported image as png
